# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_auto_20170609_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailsubmission',
            name='opened',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
