# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailchimp_id', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('is_activist_source', models.BooleanField(default=False)),
            ],
        ),
    ]
