# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 08:27
from __future__ import unicode_literals

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Activist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('address', address.models.AddressField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('active', models.BooleanField()),
                ('next_state', models.CharField(choices=[(b'2', b'attended'), (b'4', b'cancelled'), (b'1', b'confirmed'), (b'3', b'noshow'), (b'0', b'prospective')], max_length=1)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='crm.Action')),
            ],
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('control_type', models.CharField(choices=[(b'1', b'boolean'), (b'2', b'multiple_choice'), (b'3', b'options'), (b'0', b'text')], max_length=1)),
                ('control_data', models.TextField(blank=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='crm.Form')),
            ],
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('activist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='crm.Activist')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='crm.FormField')),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[(b'2', b'attended'), (b'4', b'cancelled'), (b'1', b'confirmed'), (b'3', b'noshow'), (b'0', b'prospective')], max_length=1)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='crm.Action')),
                ('activist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='crm.Activist')),
            ],
        ),
    ]
