# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='state',
            field=models.IntegerField(choices=[(b'2', b'attended'), (b'4', b'cancelled'), (b'1', b'confirmed'), (b'3', b'noshow'), (b'0', b'prospective')]),
        ),
    ]
