# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def create_default_campaign(apps, schema_editor):
    Campaign = apps.get_model("crm", "Campaign")
    Campaign.objects.create(name="Unnamed Campaign")

class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20170517_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(b'1', b'active'), (b'2', b'inactive'), (b'0', b'prospective'), (b'3', b'removed')])),
                ('activist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_memberships', to='crm.Activist')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_memberships', to='crm.Campaign')),
            ],
        ),
        migrations.RunPython(create_default_campaign),
        migrations.AddField(
            model_name='action',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.Campaign'),
            preserve_default=False,
        ),
    ]
