# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20170518_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='next_state',
            field=models.IntegerField(choices=[(b'2', b'attended'), (b'4', b'cancelled'), (b'1', b'confirmed'), (b'3', b'noshow'), (b'0', b'prospective')]),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='control_type',
            field=models.IntegerField(choices=[(b'1', b'boolean'), (b'2', b'multiple_choice'), (b'3', b'options'), (b'0', b'text')]),
        ),
    ]
