# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20170518_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignmember',
            name='state',
            field=models.IntegerField(choices=[(1, b'active'), (2, b'inactive'), (0, b'prospective'), (3, b'removed')]),
        ),
        migrations.AlterField(
            model_name='form',
            name='next_state',
            field=models.IntegerField(choices=[(2, b'attended'), (4, b'cancelled'), (1, b'confirmed'), (3, b'noshow'), (0, b'prospective')]),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='control_type',
            field=models.IntegerField(choices=[(1, b'boolean'), (2, b'multiple_choice'), (3, b'options'), (0, b'text')]),
        ),
        migrations.AlterField(
            model_name='signup',
            name='state',
            field=models.IntegerField(choices=[(2, b'attended'), (4, b'cancelled'), (1, b'confirmed'), (3, b'noshow'), (0, b'prospective')]),
        ),
    ]
