# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20170518_0319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['-date', 'name']},
        ),
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='activist',
            name='do_not_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='form',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
