# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20170609_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignmember',
            name='activist',
        ),
        migrations.RemoveField(
            model_name='campaignmember',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='action',
            name='campaign',
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
        migrations.DeleteModel(
            name='CampaignMember',
        ),
    ]
