# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 06:02
from __future__ import unicode_literals

import crm.models
from django.db import migrations
import enumfields.fields
from enumfields import Enum

class FormControlType(Enum):
   text = 0
   boolean = 1
   multiple_choice = 2
   options = 3

class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20170610_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='next_state',
            field=enumfields.fields.EnumIntegerField(enum=crm.models.SignupState),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='control_type',
            field=enumfields.fields.EnumIntegerField(enum=FormControlType),
        ),
        migrations.AlterField(
            model_name='signup',
            name='state',
            field=enumfields.fields.EnumIntegerField(enum=crm.models.SignupState),
        ),
    ]
