# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 05:40
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.models.functions import Concat
import django.utils.timezone

def dedupe_signups(apps, schema_editor):
    SignupModel = apps.get_model('crm', 'Signup')
    signupsWithDupes = SignupModel.objects\
                .values('activist', 'action') \
                .annotate(dedupe=Concat(models.F('activist'), models.Value(','), models.F('action'))).annotate(count=models.Count('dedupe'))\
                .filter(count__gt=1)
    for dupe in signupsWithDupes:
        theseDuplicates = SignupModel.objects.filter(activist_id=dupe['activist'],
                action_id=dupe['action']).order_by('-state')
        for d in theseDuplicates[1:]:
            d.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20170617_0602'),
    ]

    operations = [
        migrations.RunPython(dedupe_signups, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name='signup',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='signup',
            unique_together=set([('activist', 'action')]),
        ),
    ]
