# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20170617_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='signup',
            unique_together=set([('activist', 'action')]),
        ),
    ]
