# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0005_auto_20170518_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocd_id', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('type', models.IntegerField(choices=[(0, b'local_council'), (1, b'local_executive'), (7, b'national_executive'), (5, b'national_lower'), (6, b'national_upper'), (4, b'state_executive'), (2, b'state_lower'), (3, b'state_upper')])),
            ],
        ),
        migrations.CreateModel(
            name='DistrictMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('activist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_memberships', to='crm.Activist')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_memberships', to='districting.District')),
            ],
        ),
    ]
