# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 06:02
from __future__ import unicode_literals

import districting.models
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('districting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='type',
            field=enumfields.fields.EnumIntegerField(enum=districting.models.DistrictType),
        ),
    ]
